CREATE TABLE IF NOT EXISTS game_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL UNIQUE,
    status VARCHAR(16) NOT NULL CHECK (status IN ('PLAYING', 'WIN', 'LOSE')),
    email VARCHAR(254),
    started_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP(6) WITH TIME ZONE,
    remaining_seconds INTEGER CHECK (remaining_seconds BETWEEN 0 AND 90),
    last_seen_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT valid_session_outcome CHECK (
        (status = 'PLAYING' AND finished_at IS NULL AND remaining_seconds IS NULL)
        OR (status = 'WIN' AND finished_at IS NOT NULL AND remaining_seconds IS NOT NULL)
        OR (status = 'LOSE' AND finished_at IS NOT NULL AND remaining_seconds IS NOT NULL AND remaining_seconds = 0)
    )
);
