import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,STATES} from '../engine.js';
import {room} from '../room.js';
function setup(){let now=100;const game=new Game(room,()=>now);return {game,advance:ms=>{now+=ms;game.tick();}};}
test('loading waits indefinitely; duplicate start cannot extend the deadline',()=>{const {game,advance}=setup();advance(200000);assert.equal(game.remaining,90000);assert.equal(game.state,STATES.READY);assert.equal(game.start(),true);advance(2500);assert.equal(game.start(),false);assert.equal(game.remaining,87500);});
test('clues are reusable and inspection does not pause elapsed time',()=>{const {game,advance}=setup();game.start();game.inspect('note');game.inspect('note');assert.equal(game.seen.size,1);advance(12345);assert.equal(game.remaining,77655);});
test('wrong code costs exactly five seconds; duplicate enter has no extra penalty',()=>{const {game}=setup();game.start();game.inspect('keypad');'1111'.split('').forEach(v=>game.digit(v));game.submit();assert.equal(game.remaining,85000);assert.equal(game.message,'WRONG CODE');game.submit();assert.equal(game.remaining,85000);});
test('one solution follows clue order and calibration, success freezes time',()=>{const {game,advance}=setup();const reference={moon:2,star:7,eye:3,sun:5};const solution=['moon','star','eye','sun'].map(s=>reference[s]+1).join('');assert.equal(solution,room.code);game.start();advance(2300);game.inspect('keypad');solution.split('').forEach(v=>game.digit(v));assert.equal(game.submit(),true);advance(100000);assert.equal(game.state,STATES.SUCCESS);assert.equal(game.remaining,87700);});
test('large elapsed jump fails, and a late correct entry cannot succeed',()=>{const {game,advance}=setup();game.start();game.inspect('keypad');room.code.split('').forEach(v=>game.digit(v));advance(90001);game.submit();assert.equal(game.remaining,0);assert.equal(game.state,STATES.FAILED);});
test('wrong entry near expiry fails immediately; reset returns to ready',()=>{const {game,advance}=setup();game.start();advance(86000);game.inspect('keypad');'0000'.split('').forEach(v=>game.digit(v));game.submit();assert.equal(game.state,STATES.FAILED);game.reset();advance(500000);assert.equal(game.state,STATES.READY);assert.equal(game.remaining,90000);assert.equal(game.seen.size,0);});
test('partial entries and extra digits cannot cause duplicate submission',()=>{const {game}=setup();game.start();game.inspect('keypad');game.digit('3');game.submit();assert.equal(game.remaining,90000);game.clear();assert.equal(game.input,'');'384600'.split('').forEach(v=>game.digit(v));assert.equal(game.input,'3846');game.submit();game.submit();assert.equal(game.state,STATES.SUCCESS);});
